// Fill in  your WiFi networks SSID and password
#define SECRET_SSID "WiFiHoneyLab"
#define SECRET_PASS "@ur0w_nRisk"
// #define SECRET_SSID "marvelous"
// #define SECRET_PASS "univmavqq"

#define DEVICE_ID 2

// Fill in the hostname of your AWS IoT broker
#define SECRET_BROKER "a2ur4syhf6f7zo-ats.iot.us-east-1.amazonaws.com"
#define DEFAULT_BROKER_ADDRESS_SECURE_AUTH "a2ur4syhf6f7zo-ats.iot.us-east-1.amazonaws.com"

// Fill in the boards public certificate
const char SECRET_CERTIFICATE[] = R"(
-----BEGIN CERTIFICATE-----
MIICzDCCAbSgAwIBAgIUCFMZZIKeAvVBYxKuQy45qU9A2uwwDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTIzMDgyNzE0MzQw
MloXDTQ5MTIzMTIzNTk1OVowXDELMAkGA1UEBhMCY2ExCzAJBgNVBAgTAnFjMQsw
CQYDVQQHEwJxYzENMAsGA1UEChMEbGFiczENMAsGA1UECxMEbGFiczEVMBMGA1UE
AxMMdG94aWNhaXJtb24yMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEE54p3+Rq
pFLYLw4WqCL20o82g7RzjKViQHrrdni0jCGfoPR1axlbrrV+HVOGXsT1zdKJpZ6U
eJfVHlaFZCiyvqNgMF4wHwYDVR0jBBgwFoAUWY/iHGMsQkCdQIgrZJt7+1mxAhAw
HQYDVR0OBBYEFDIByYuFkR4MVVZDtdEgo8pXdmxCMAwGA1UdEwEB/wQCMAAwDgYD
VR0PAQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAeVWBKPs9mpOMoDmOsZ93p
Xd0UqIDbL0UNzpmfmoSKSdeEDSpSfO0/6Jl2egMoTVRFlKlYJoL/a/YELxBWNL3G
BQXE2yo4oiD+XfAa5zprggfYSsPaMjGCmRtHs41MqpaoYwqmrmaSZtuXPiyz619B
JlFWEfrtaEVfSSyAlnUFunyX8X5YNW8jgd92ph+fv4k96DY83jBXiBTf23nOduTG
8RJ+nlzJIGd0BWe5EK3kKopwnDKwtthDcdDrqLh0ctRY/Mmp+cGfNRd7OVhv9CAe
Y7pIB9wR9L2PSQJQ7U+sAdKKuv111myCbp/f4dzMIFETX/1fsJ0Gc1gmUPqiakS4
-----END CERTIFICATE-----
)";
